add Kotlin libs & bump parents
rbkmoney/rbk-templator pull request #48
Opened 2021-06-01 12:43 UTC by ElenaKushchenko

2021-06-01 12:49 UTC, PospolitaNV commented on plop-templates/adapter/payout/pom.xml
> +        <version>2.0.0</version>
Это пока что лучше не трогать, это под java 15 ("Не ешь, это на Новый Год")

2021-06-01 12:51 UTC, ElenaKushchenko commented on plop-templates/adapter/payout/pom.xml
> +        <version>2.0.0</version>
ок

2021-06-01 13:01 UTC, PospolitaNV requested changes

2021-06-01 13:01 UTC, PospolitaNV commented on plop-templates/library/library-pom.xml
>          {{/if_eq}}
можно версии в service-dependencies закинуть, подразумевается что они там должны меняться

2021-06-01 13:01 UTC, PospolitaNV commented on plop-templates/adapter/payout/pom.xml
> +        {{/if_eq}}
можно версии в service-dependencies закинуть, подразумевается что они там должны меняться

2021-06-01 13:01 UTC, PospolitaNV commented on plop-templates/library/library-pom.xml
>          {{/if_eq}}
Но тут кажется либа, тут не нужно)

2021-06-01 13:01 UTC, PospolitaNV commented on plop-templates/service/service-pom.xml
> +        <version>2.0.0</version>
тоже ещё рановато. 1.2.3 последняя

2021-06-02 13:03 UTC, PospolitaNV approved these changes

2021-06-15 15:55 UTC, merged