Add OpenAPI generator
rbkmoney/rbk-templator pull request #53
Opened 2021-07-08 12:36 UTC by vitaxa

2021-07-14 15:43 UTC, PospolitaNV requested changes

2021-07-15 07:42 UTC, vitaxa commented on generators/openapi-generator-3.0.js
> +    },
Просто тогда выглядит единообразно с остальными проектами swag, service и так далее. Думаешь все равно стоит убрать?

2021-07-15 07:43 UTC, vitaxa commented on package.json
> +        "simple-git": "^1.132.0"
Локально тестил, все збс. Кажется у меня наоборот были проблемы со старой версией plop

2021-07-15 07:57 UTC, vitaxa commented on plop-templates/openapi/openapi-pom.xml
> +        <version>1.0.5</version>
Мб прост наш library-parent-pom сойдет?

2021-07-15 08:01 UTC, vitaxa commented on plop-templates/openapi/openapi-pom.xml
> +    <artifactId>openapi-{{kebabCase name}}</artifactId>
Вот тут надо подумать. Для генератора мне кажется важным, чтобы название отражало, что это именно openapi, а не swag. А вот репозитории я называю как обычно, чтоб было проще искать

2021-07-15 12:28 UTC, PospolitaNV commented on plop-templates/openapi/openapi-pom.xml
> +        <version>1.0.5</version>
Надо потестить, да)

2021-07-15 12:28 UTC, PospolitaNV commented on plop-templates/openapi/openapi-pom.xml
> +    <artifactId>openapi-{{kebabCase name}}</artifactId>
Не, скорей одинаково с репой нужно назвать. Предлагаю OPEN-API в описании генератора оставить)

2021-07-15 12:29 UTC, PospolitaNV commented on plop-templates/openapi/openapi-pom.xml
> +    <artifactId>openapi-{{kebabCase name}}</artifactId>
Сейчас тем более swag 3.0 и openapi 3.0 шаблоны почему-то, насколько я знаю swag 3.0 нет

2021-08-05 11:44 UTC, vitaxa commented on plop-templates/openapi/openapi-pom.xml
> +        <version>1.0.5</version>
потестил 🤦

2021-08-05 11:47 UTC, vitaxa commented on plop-templates/openapi/openapi-pom.xml
> +    <artifactId>openapi-{{kebabCase name}}</artifactId>
Везде поменял на swag, чтоб меньше потенциальных проблем было

2021-08-06 11:00 UTC, PospolitaNV approved these changes

2021-08-06 11:44 UTC, merged